# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ -r "$ZDOTDIR/plugins/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
  source "$ZDOTDIR/plugins/powerlevel10k/powerlevel10k.zsh-theme"
fi

source "$ZDOTDIR/zshrc.sh"

if [ -f $ZDOTDIR/.p10k.zsh ]; then
    source $ZDOTDIR/.p10k.zsh
else
    p10k-configure
fi

if command -v zmx &>/dev/null; then
  eval "$(zmx completions zsh)"
fi

if command -v zoxide &>/dev/null; then
  eval "$(zoxide init zsh)"
fi
